
server:
  port: 8084

spring:

  datasource:
    name: jtsys
    url: jdbc:mysql://localhost:3306/gw_game_ppc?useLegacyDatetimeCode=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: consumer-server
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-8081.com:8081/eureka,http://eureka-8082.com:8082/eureka