spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html

  datasource:
    name: jtsys
    url: jdbc:mysql://localhost:3306/jtsys?useLegacyDatetimeCode=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: product-server

server:
  port: 8088

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-8081.com:8081/eureka,http://eureka-8082.com:8082/eureka

instance:
  prefer-ip-address: true

