server:
  port: 8082

eureka:
  instance:
    hostname: eureka-8082.com #eureka-8082.com:8082
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-8081.com:8081/eureka/






