server:
  port: 8081

eureka:
  instance:
    hostname: eureka-8081.com #eureka-8081.com:8081
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-8082.com:8082/eureka/







